In [26]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
data = pd.DataFrame({"text":["Cats are beautiful creatures.", "Dogs are loyal pets.", "Birds can fly in the sky."]})

In [4]:
data

text
0  Cats are beautiful creatures.
1           Dogs are loyal pets.
2      Birds can fly in the sky.

In [7]:
bow=CountVectorizer()

In [8]:
document_matrix=bow.fit_transform(data["text"])

In [9]:
document_matrix

<3x13 sparse matrix of type '<class 'numpy.int64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [11]:
bow.vocabulary_

{'cats': 4,
 'are': 0,
 'beautiful': 1,
 'creatures': 5,
 'dogs': 6,
 'loyal': 9,
 'pets': 10,
 'birds': 2,
 'can': 3,
 'fly': 7,
 'in': 8,
 'the': 12,
 'sky': 11}

In [12]:
document_matrix[0].toarray()

array([[1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0]])

In [13]:
document_matrix[1].toarray()

array([[1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0]])

In [14]:
document_matrix[2].toarray()

array([[0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1]])

In [17]:
bigram=CountVectorizer(ngram_range=(2,2))

In [18]:
bigramvocab=bigram.fit_transform(data["text"])

In [19]:
bigram.vocabulary_

{'cats are': 5,
 'are beautiful': 0,
 'beautiful creatures': 2,
 'dogs are': 6,
 'are loyal': 1,
 'loyal pets': 9,
 'birds can': 3,
 'can fly': 4,
 'fly in': 7,
 'in the': 8,
 'the sky': 10}

In [20]:
trigram=CountVectorizer(ngram_range=(3,3))

In [21]:
trigramdata=trigram.fit_transform(data["text"])

In [22]:
trigram.vocabulary_

{'cats are beautiful': 4,
 'are beautiful creatures': 0,
 'dogs are loyal': 5,
 'are loyal pets': 1,
 'birds can fly': 2,
 'can fly in': 3,
 'fly in the': 6,
 'in the sky': 7}

In [23]:
mix=CountVectorizer(ngram_range=(1,2))

In [24]:
mix_vocab=mix.fit_transform(data["text"])

In [25]:
mix.vocabulary_

{'cats': 9,
 'are': 0,
 'beautiful': 3,
 'creatures': 11,
 'cats are': 10,
 'are beautiful': 1,
 'beautiful creatures': 4,
 'dogs': 12,
 'loyal': 18,
 'pets': 20,
 'dogs are': 13,
 'are loyal': 2,
 'loyal pets': 19,
 'birds': 5,
 'can': 7,
 'fly': 14,
 'in': 16,
 'the': 22,
 'sky': 21,
 'birds can': 6,
 'can fly': 8,
 'fly in': 15,
 'in the': 17,
 'the sky': 23}

In [27]:
tfidf=TfidfVectorizer()

In [29]:
tfidf.fit_transform(data["text"]).toarray()

array([[0.40204024, 0.52863461, 0.        , 0.        , 0.52863461,
        0.52863461, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.40204024, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.52863461, 0.        , 0.        , 0.52863461,
        0.52863461, 0.        , 0.        ],
       [0.        , 0.        , 0.40824829, 0.40824829, 0.        ,
        0.        , 0.        , 0.40824829, 0.40824829, 0.        ,
        0.        , 0.40824829, 0.40824829]])

In [30]:
tfidf.get_feature_names_out()


array(['are', 'beautiful', 'birds', 'can', 'cats', 'creatures', 'dogs',
       'fly', 'in', 'loyal', 'pets', 'sky', 'the'], dtype=object)

In [31]:
tfidf.idf_

array([1.28768207, 1.69314718, 1.69314718, 1.69314718, 1.69314718,
       1.69314718, 1.69314718, 1.69314718, 1.69314718, 1.69314718,
       1.69314718, 1.69314718, 1.69314718])